Import('target_env', 'project_env', 'custom_tests')

#######################################################
# Create CMMT environment
#######################################################
lib_env = target_env.Clone()

#######################################################
# Configure lib environment
#######################################################

#######################################################
# Build IOS filters
#######################################################
libs = [
    lib_env.SharedLibrary('ios_filter', lib_env.Glob('*.cc')),
    lib_env.StaticLibrary('ios_filter', lib_env.Glob('*.cc'))
]

#######################################################
# Install IOS filter libaries
#######################################################
lib_env.Install(lib_env['install_libdir'], libs)

project_env['sysinstall_lib'] = libs
